# Case Study 2 (functions)

## Task 1
A robot moves in a plane starting from the origin point(0,0). The robot can move UP,DOWN,LEFT,RIGHT. Write a program that takes how many steps the robot walks in each direction then print out the distance between the robot’s current position and the origin.

Hint: use the math module.

In [2]:
# Porgram
from math import sqrt
def distance_from_origin(up=0, down=0, left=0, right=0):
    return sqrt((up-down)**2 + (left-right)**2)

# Test
distance_from_origin(up=1, down=11, left=10)

14.142135623730951

## Task 2

Some data is stored in a sorted list, write a program that takes the list and the element and looks for the element in the given list and returns it.


In [1]:
## Task 2

## Task 3

A weather forecasting organization want to find whether it is dark outside or not. Write a program that once called, print outs whether its dark or not outside. 

Hint: use the time module

In [3]:
# Program
## Assuming its dark after 6 p.m. and before 6 a.m.
from datetime import datetime
def is_it_dark_outside():
    h = datetime.now().hour
    if h > 18 or h < 6:
        print("It's dark outside")
    else:
        print("It's not dark outside")

# Test
is_it_dark_outside()

It's dark outside


## Task 4

Write a program that finds the distance between two points if their longitude and latitude is given. 

Hint: use the math module


In [4]:
# Program
from math import sin, cos, atan2, sqrt, radians
def distance_between_two_points(p, p0=(0,0)):

    p_r = (radians(p[0]), radians(p[1]))
    p0_r = (radians(p0[0]), radians(p0[1]))
    
    diff_lat_r = p_r[0] - p0_r[0]
    diff_lng_r = p_r[1] - p0_r[1]

    a = (sin(diff_lat_r/2))**2 + cos(p_r[0]) * cos(p0_r[0]) * (sin(diff_lng_r/2))**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))

    R = 6373.0 # Raduis of earth
    d = R * c

    return print("Distance is %.3f km." % d ) 


# Test
distance_between_two_points((52.22,21.01),(52.40,16.92))

Distance is 278.821 km.


## Task 5

Design a software for bank system. That gives the user the following options: cash withdraw, cash deposit and changing the password. According to the user’s input, the software should provide the required output

In [5]:
# Task 5 sol here...

## Task 6

Write a function which find all the numbers that are divisible by 7 but are not multiples of 5, between two given numbers, the function should print those numbers in a comma separated sequence on a single line.

In [6]:
# Program
def my_func_6(start, end):
    if start >= end:
        raise ValueError
    
    sol = []
    for i in range(start, end+1):
        if i % 7 == 0 and i % 5 != 0:
            sol.append(i)
        i += 1
    
    print(*sol, sep=",")

# Test
my_func_6(1,80)

7,14,21,28,42,49,56,63,77


## Task 7

Write a program that returns the factorial of a given number.

In [7]:
# Program
def fact(n):
    if n < 0:
        raise ValueError
    sol = 1
    for i in range(1,n+1):
        sol *= i
    return sol

# Test
fact(5)

120

## Task 8, 9

Write a program that takes 2 digits, X,Y as input and generates a 2 dimensional array. The element value in the i-th row and j-th column of the array should be i*j. 

#### Example:

```
[[0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4], 
 [0, 2, 4, 6, 8]]
```

In [8]:
# Program
import numpy as np
def my_func_7(x,y):
    arr = np.zeros((x,y), dtype=int)

    for row in range(x):
        for col in range(y):
            arr[row][col] = int(row*col)

    print(arr)

# Test
my_func_7(3,5)


[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


## Task 10, 11

Write a function that accepts a list of words as input and prints the words in a comma-seperated sequence after sorting them alphabetically. 

Example:
Suppose the following input is supplied to the program: `without,hello,bag,world` Then, the output should be: `bag,hello,without,world`




In [9]:
# Program
def my_func_10(input_str):
    input_list = input_str.split(',')
    print(*sorted(input_list), sep=",")

# Test
my_func_10('without,hello,bag,world')

bag,hello,without,world


## Task 12

Write a program that accepts a sequence of lines as input and prints the lines after making all character in the sentence capitalized. Example:

Suppose the following input is supplied to the program:

```
Hello world
Practice makes perfect
```

Then, the output should be:
```
HELLO WORLD
PRACTICE MAKES PERFEC
```

In [10]:
# Program
def my_func_14(lines):
    for line in lines:
        upper = line.upper()
        print(upper)




# Test
my_func_14(["My Sentence!", "other stuff"])

MY SENTENCE!
OTHER STUFF


## Task 13

Write a function that accepts a sequence of comma separated 4 digit binary numbers as its input, and then checks whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:

`0100,0011,1010,1001`

Then the output should be:

`1010`

In [11]:
# Program
def my_func_13(input_str):
    input_list = input_str.split(",")
    sol = []
    for el in input_list:
        if int(el, 2) % 5 == 0:
            sol.append(el)
    return sol
# Test
s = my_func_13("0100,0011,1010,1001")
print(*s, sep=",")
        

1010


## Task 14

Write a function that accepts a sentence and calculate the number of upper case letters and lower case letters in that sentence. 

Example :

`Hello world!`

Then, the output should be:

```
UPPER CASE 1
LOWER CASE 9
```

In [12]:
# Program
def my_func_14(sentence):
    upper = 0
    lower = 0
    for char in sentence:
        if char.isupper():
            upper += 1
        elif char.islower():
            lower += 1
    
    print(f"UPPER CASE {upper}")
    print(f"LOWER CASE {lower}")


# Test
my_func_14("My Sentence!")

UPPER CASE 2
LOWER CASE 8


## Task 15
Give an example of the function fsum and sum from the math library.

In [13]:
from math import fsum

# Sum example
listA = list(range(1,11)) # [1..10]
sumA = sum(listA)
fsumA = math.fsum(listA)

print(f"List A -> sum: {sumA}, fsum: {fsumA}")

listB = [1.5, 2.5, 3.5, 0.03]
sumB = sum(listB)
fsumB = math.fsum(listB)

print(f"List B -> sum: {sumB}, fsum: {fsumB}")

## fsum will always return a float



NameError: name 'math' is not defined